# Pandas Tutorial

Shouvik Mani <br>
September 24, 2021 <br>
COMS 4995: Applied Machine Learning, Columbia University

In [1]:
import numpy as np
import pandas as pd

### 1. DataFrames and Series

DataFrames and Series are the fundamental data structures of Pandas. A Pandas DataFrame represents a data matrix, but unlike a Numpy matrix, a DataFrame has named columns and rows (indices).

Let's read in a DataFrame from a CSV file. This is a dataset on daily COVID-19 vaccinations by country. Source: https://www.kaggle.com/gpreda/covid-world-vaccination-progress?select=country_vaccinations.csv.

In [2]:
# Read in a DataFrame from a csv file
vaccine_df = pd.read_csv('data/covid_vaccinations/country_vaccinations.csv')
vaccine_df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45979,Zimbabwe,ZWE,2021-09-16,4964302.0,2930550.0,2033752.0,108486.0,51755.0,32.89,19.42,13.48,3429.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45980,Zimbabwe,ZWE,2021-09-17,NaN,NaN,NaN,NaN,45993.0,NaN,NaN,NaN,3047.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45981,Zimbabwe,ZWE,2021-09-18,4992501.0,2940750.0,2051751.0,NaN,40514.0,33.08,19.49,13.59,2684.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45982,Zimbabwe,ZWE,2021-09-19,5015041.0,2948725.0,2066316.0,22540.0,40630.0,33.23,19.54,13.69,2692.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45983,Zimbabwe,ZWE,2021-09-20,5044809.0,2961845.0,2082964.0,29768.0,41779.0,33.43,19.63,13.80,2768.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

Dimensions of DataFrame

In [3]:
vaccine_df.shape

(45984, 15)

Type of each column in DataFrame

In [4]:
vaccine_df.dtypes

country                                 object
iso_code                                object
date                                    object
total_vaccinations                     float64
people_vaccinated                      float64
people_fully_vaccinated                float64
daily_vaccinations_raw                 float64
daily_vaccinations                     float64
total_vaccinations_per_hundred         float64
people_vaccinated_per_hundred          float64
people_fully_vaccinated_per_hundred    float64
daily_vaccinations_per_million         float64
vaccines                                object
source_name                             object
source_website                          object
dtype: object

Summary statistics for each column

In [5]:
vaccine_df.describe()

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,2.508400e+04,2.394600e+04,2.104800e+04,2.060000e+04,4.567700e+04,25084.000000,23946.000000,21048.000000,45677.000000
mean,2.048794e+07,8.757993e+06,5.583303e+06,2.597850e+05,1.308535e+05,43.740659,26.569498,19.689742,3547.603520
std,1.173603e+08,3.430173e+07,2.211721e+07,1.317281e+06,8.758538e+05,45.044427,24.458658,21.467135,4429.261509
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,2.077678e+05,1.668525e+05,8.035850e+04,4.898000e+03,8.710000e+02,5.270000,4.112500,2.300000,505.000000
50%,1.459863e+06,9.981035e+05,6.352150e+05,2.410650e+04,6.774000e+03,26.440000,18.600000,10.645000,2191.000000
75%,7.737194e+06,4.679778e+06,3.270408e+06,1.116888e+05,4.169500e+04,73.442500,46.300000,32.252500,5307.000000
max,2.180986e+09,1.100842e+09,1.022207e+09,2.474100e+07,2.242429e+07,235.390000,118.270000,117.120000,117497.000000

Head and tail of DataFrame

In [6]:
vaccine_df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...

In [7]:
vaccine_df.tail()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
45979,Zimbabwe,ZWE,2021-09-16,4964302.0,2930550.0,2033752.0,108486.0,51755.0,32.89,19.42,13.48,3429.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45980,Zimbabwe,ZWE,2021-09-17,NaN,NaN,NaN,NaN,45993.0,NaN,NaN,NaN,3047.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45981,Zimbabwe,ZWE,2021-09-18,4992501.0,2940750.0,2051751.0,NaN,40514.0,33.08,19.49,13.59,2684.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45982,Zimbabwe,ZWE,2021-09-19,5015041.0,2948725.0,2066316.0,22540.0,40630.0,33.23,19.54,13.69,2692.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
45983,Zimbabwe,ZWE,2021-09-20,5044809.0,2961845.0,2082964.0,29768.0,41779.0,33.43,19.63,13.80,2768.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

A Series represents a column in a DataFrame, and is analogous to a vector. It is also named and has row indices.

In [8]:
vaccine_df['country']

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
45979       Zimbabwe
45980       Zimbabwe
45981       Zimbabwe
45982       Zimbabwe
45983       Zimbabwe
Name: country, Length: 45984, dtype: object

Besides reading in DataFrames and Series from a CSV file, we can also create them from scratch.

In [9]:
players = ['Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Kylian Mbappe', 'Mohamed Salah']
players = pd.Series(players)   # Creates a Series of players
players

0         Lionel Messi
1    Cristiano Ronaldo
2               Neymar
3        Kylian Mbappe
4        Mohamed Salah
dtype: object

In [10]:
player_teams = [['Lionel Messi', 'Paris Saint-Germain', 34],
                ['Cristiano Ronaldo', 'Manchester United', 36],
                ['Neymar', 'Paris Saint-Germain', 29],
                ['Kylian Mbappe', 'Paris Saint-Germain', 22],
                ['Mohamed Salah', 'Liverpool', 29]]

# Creates a DataFrame of players, teams, and ages
player_teams_df = pd.DataFrame(player_teams, columns=['Name', 'Team', 'Age'])
player_teams_df

                Name                 Team  Age
0       Lionel Messi  Paris Saint-Germain   34
1  Cristiano Ronaldo    Manchester United   36
2             Neymar  Paris Saint-Germain   29
3      Kylian Mbappe  Paris Saint-Germain   22
4      Mohamed Salah            Liverpool   29

### 2. Indexing and Iterating

The index of a DataFrame or Series serves as a (not necessarily unique) identifier for each row. By default, a DataFrame has the index 0, 1, 2, ..., but we can also set the index as we please.

In [11]:
# Default index is 0, 1, 2, ..., 4
list(player_teams_df.index)

[0, 1, 2, 3, 4]

Let's set the index of this DataFrame to the player's names.

In [12]:
player_teams_df = player_teams_df.set_index('Name')
player_teams_df   # now the DataFrame is indexed by player name

                                  Team  Age
Name
Lionel Messi       Paris Saint-Germain   34
Cristiano Ronaldo    Manchester United   36
Neymar             Paris Saint-Germain   29
Kylian Mbappe      Paris Saint-Germain   22
Mohamed Salah                Liverpool   29

To access an element by it's DataFrame index, use the `.loc` method.

In [13]:
player_teams_df.loc['Neymar']

Team    Paris Saint-Germain
Age                      29
Name: Neymar, dtype: object

In [14]:
player_teams_df.loc[['Lionel Messi', 'Neymar', 'Kylian Mbappe']]

                              Team  Age
Name
Lionel Messi   Paris Saint-Germain   34
Neymar         Paris Saint-Germain   29
Kylian Mbappe  Paris Saint-Germain   22

To access an element by it's numeric index, use the `.iloc`  method.

In [15]:
player_teams_df.iloc[2]

Team    Paris Saint-Germain
Age                      29
Name: Neymar, dtype: object

In [16]:
player_teams_df.iloc[[2, 3, 4]]

                              Team  Age
Name
Neymar         Paris Saint-Germain   29
Kylian Mbappe  Paris Saint-Germain   22
Mohamed Salah            Liverpool   29

We can iterate over a Series using the `.iteritems` method.

In [17]:
for index, name in players.iteritems():
    print(index, name)

0 Lionel Messi
1 Cristiano Ronaldo
2 Neymar
3 Kylian Mbappe
4 Mohamed Salah

We can iterate over a DataFrame using the `.iterrows` method.

In [18]:
for index, row in player_teams_df.iterrows():
    print(index, '\n', row['Team'], '\n', row['Age'], '\n')

Lionel Messi
 Paris Saint-Germain
 34

Cristiano Ronaldo
 Manchester United
 36

Neymar
 Paris Saint-Germain
 29

Kylian Mbappe
 Paris Saint-Germain
 22

Mohamed Salah
 Liverpool
 29

### 3. Filtering and Sorting

Pandas offers a flexible interface for filtering Series and DataFrames based on various conditions.

In [19]:
# Filter vaccine_df to rows where country is 'United States'
vaccine_df_usa = vaccine_df[vaccine_df['country'] == 'United States']
print(vaccine_df_usa.shape)
vaccine_df_usa.head()

(275, 15)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
43869,United States,USA,2020-12-20,556208.0,556208.0,NaN,NaN,NaN,0.17,0.17,NaN,NaN,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43870,United States,USA,2020-12-21,614117.0,614117.0,NaN,57909.0,57909.0,0.18,0.18,NaN,172.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43871,United States,USA,2020-12-22,NaN,NaN,NaN,NaN,127432.0,NaN,NaN,NaN,379.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43872,United States,USA,2020-12-23,1008025.0,1008025.0,NaN,NaN,150606.0,0.30,0.30,NaN,448.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43873,United States,USA,2020-12-24,NaN,NaN,NaN,NaN,191001.0,NaN,NaN,NaN,568.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...

In [20]:
# Filter vaccine_df to rows where country is 'United States' OR country is 'Mexico'
vaccine_df_usa_mex = vaccine_df[(vaccine_df['country'] == 'United States') | (vaccine_df['country'] == 'Mexico')]
print(vaccine_df_usa_mex.shape)
vaccine_df_usa_mex.head()

(544, 15)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
26400,Mexico,MEX,2020-12-24,2924.0,2924.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"CanSino, Johnson&Johnson, Moderna, Oxford/Astr...",Secretary of Health,http://www.gob.mx/cms/uploads/attachment/file/...
26401,Mexico,MEX,2020-12-25,NaN,NaN,NaN,NaN,1300.0,NaN,NaN,NaN,10.0,"CanSino, Johnson&Johnson, Moderna, Oxford/Astr...",Secretary of Health,http://www.gob.mx/cms/uploads/attachment/file/...
26402,Mexico,MEX,2020-12-26,NaN,NaN,NaN,NaN,1300.0,NaN,NaN,NaN,10.0,"CanSino, Johnson&Johnson, Moderna, Oxford/Astr...",Secretary of Health,http://www.gob.mx/cms/uploads/attachment/file/...
26403,Mexico,MEX,2020-12-27,6824.0,6824.0,NaN,NaN,1300.0,0.01,0.01,NaN,10.0,"CanSino, Johnson&Johnson, Moderna, Oxford/Astr...",Secretary of Health,http://www.gob.mx/cms/uploads/attachment/file/...
26404,Mexico,MEX,2020-12-28,9579.0,9579.0,NaN,2755.0,1664.0,0.01,0.01,NaN,13.0,"CanSino, Johnson&Johnson, Moderna, Oxford/Astr...",Secretary of Health,http://www.gob.mx/cms/uploads/attachment/file/...

In [21]:
# Filter vaccine_df to rows where country is 'United States' AND dates after 2021-01-01
vaccine_df_usa = vaccine_df[(vaccine_df['country'] == 'United States') & (vaccine_df['date'] >= '2021-01-01')]
print(vaccine_df_usa.shape)
vaccine_df_usa.head()

(263, 15)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
43881,United States,USA,2021-01-01,NaN,NaN,NaN,NaN,302329.0,NaN,NaN,NaN,899.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43882,United States,USA,2021-01-02,4225756.0,4225756.0,NaN,NaN,325882.0,1.26,1.26,NaN,969.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43883,United States,USA,2021-01-03,NaN,NaN,NaN,NaN,336949.0,NaN,NaN,NaN,1002.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43884,United States,USA,2021-01-04,4563260.0,4563260.0,NaN,NaN,348017.0,1.36,1.36,NaN,1035.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43885,United States,USA,2021-01-05,4836469.0,4836469.0,NaN,273209.0,339372.0,1.44,1.44,NaN,1009.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...

We can also sort the DataFrame with a specific column as the key.

In [22]:
vaccine_df_usa_sorted_by_daily_vacs = vaccine_df_usa.sort_values('daily_vaccinations', ascending=False)
vaccine_df_usa_sorted_by_daily_vacs.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
43983,United States,USA,2021-04-13,192282781.0,122295530.0,75322283.0,2590736.0,3384387.0,57.17,36.36,22.40,10063.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43986,United States,USA,2021-04-16,202282923.0,127743096.0,80609818.0,3965883.0,3349306.0,60.15,37.98,23.97,9959.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43985,United States,USA,2021-04-15,198317040.0,125822868.0,78498290.0,3525204.0,3348189.0,58.97,37.41,23.34,9955.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43984,United States,USA,2021-04-14,194791836.0,123917385.0,76681252.0,2509055.0,3330740.0,57.92,36.84,22.80,9903.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...
43982,United States,USA,2021-04-12,189692045.0,120848490.0,74066085.0,2644914.0,3214893.0,56.40,35.93,22.02,9559.0,"Johnson&Johnson, Moderna, Pfizer/BioNTech",Centers for Disease Control and Prevention,https://covid.cdc.gov/covid-data-tracker/COVID...

### 4. Useful Pandas Operations

View unique elements in a Series

In [24]:
vaccine_df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia',
       'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'England',
       'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France',
       'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North Macedonia', 'Northern Cyprus', 'Northern Ireland', 'Norway',
       'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wales', 'Wallis and Futuna', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

View counts of items in a Series

In [25]:
vaccine_df['country'].value_counts()

Denmark         293
Norway          292
Latvia          291
Scotland        286
England         286
               ...
Haiti            64
Tokelau          57
Niue             43
Tanzania         35
Turkmenistan      1
Name: country, Length: 222, dtype: int64

Add a column to a DataFrame

In [26]:
player_teams_df['Nationality'] = ['Argentina', 'Portugal', 'Brazil', 'France', 'Egypt']
player_teams_df

                                  Team  Age Nationality
Name
Lionel Messi       Paris Saint-Germain   34   Argentina
Cristiano Ronaldo    Manchester United   36    Portugal
Neymar             Paris Saint-Germain   29      Brazil
Kylian Mbappe      Paris Saint-Germain   22      France
Mohamed Salah                Liverpool   29       Egypt

Remove missing data

In [27]:
print(vaccine_df.shape)

# Remove rows where daily_vaccinations column has a missing entry
vaccine_df = vaccine_df.dropna(subset=['daily_vaccinations'])

print(vaccine_df.shape)
vaccine_df.head()

(45984, 15)
(45677, 15)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...
5,Afghanistan,AFG,2021-02-27,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://app.powerbi.com/view?r=eyJrIjoiYTkyM2V...

Save DataFrame to CSV

In [28]:
vaccine_df.to_csv('data/covid_vaccinations/country_vaccinations_processed.csv', index=False)

In [29]:
player_teams_df.to_csv('data/player_teams.csv')